---
- name: Installation du serveur web Php 7.0 Apache Mysql
  hosts: vps
  remote_user: root
  vars_files:
    - vars/provision_dev.yml
        
  roles:
    - { role: apt_update }
    - { role: geerlingguy.php }
    - { role: geerlingguy.apache }
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.git }
...